server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://120.53.24.212:33306/myMall?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 321261949
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml